#!/bin/sh
rm IngestData.jar
sudo mvn install clean compile assembly:single
mv target/IngestData-1.0-SNAPSHOT-jar-with-dependencies.jar ./IngestData.jar
java -jar IngestData.jar $1 $2 $3 $4 $5 $6 $7 $8 $9 $10
